# SwiftLint configuration (https://github.com/realm/SwiftLint)
included:
  - Sources
  - scripts
excluded:
  - .build
  - dist

opt_in_rules:
  - array_init
  - closure_spacing
  - collection_alignment
  - contains_over_filter_is_empty
  - contains_over_first_not_nil
  - empty_collection_literal
  - empty_count
  - empty_string
  - explicit_init
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - last_where
  - modifier_order
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - redundant_nil_coalescing
  - sorted_first_last
  - toggle_bool
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - yoda_condition

disabled_rules:
  - todo
  - trailing_comma

line_length:
  warning: 120
  error: 160
  ignores_comments: true
  ignores_urls: true

identifier_name:
  min_length: 2
  excluded: [id, x, y]

type_body_length:
  warning: 300
  error: 400

file_length:
  warning: 400
  error: 600

function_body_length:
  warning: 60
  error: 100

cyclomatic_complexity:
  warning: 12
  error: 20

force_unwrapping:
  severity: warning
